vars:
  registry: docker-registry.dun.fh
  image: findmypast/domesday

tasks:
  build:
    - cmd: docker build --force-rm -t <%=registry%>/<%=image%> .

  push:
    - cmd: docker push <%=registry%>/<%=image%>

  test:
    - cmd: docker run --rm <%=registry%>/<%=image%> npm run test:ci

  publish:
    - cmd: docker run -e NPM_USER -e NPM_PASSWORD -e NPM_EMAIL --rm <%=registry%>/<%=image%> npm run publish-to-npm
      environment:
        - NPM_USER=<%=user%>
        - NPM_PASSWORD=<%=password%>
        - NPM_EMAIL=<%=email%>
