vars:
  registry: fh1-harbor01.dun.fh
  image: findmypast/domesday

tasks:
  build:
    - description: build a docker container containing the packaged tool
    - cmd: docker build --force-rm -t <%=registry%>/<%=image%> .

  test:
    - description: run the unit tests against the packaged container
    - cmd: docker run --rm <%=registry%>/<%=image%> npm run test:ci

  push:
    - description: push the docker container to our docker registry
    - cmd: docker push <%=registry%>/<%=image%>

  publish:
    - description: publish the code as a npm package
    - cmd: docker run -e NPM_USER -e NPM_TOKEN -e NPM_EMAIL --rm <%=registry%>/<%=image%> npm run publish-to-npm
      environment:
        - NPM_USER=<%=user%>
        - NPM_TOKEN=<%=password%>
        - NPM_EMAIL=<%=email%>
